### ISSUE TITLE
Warning: file_get_contents / failed to open stream: Permission denied

### ISSUE THREAD

**Issue by germanllop** [aymanrb/php-unstructured-text-parser#10]
Hello, I'm currently using the package it's amazing, but I get a couple of warnings, but the code runs perfectly, tried with different php versions 5.6, 7.0, 7.1 and 7.2 and still got the warning:

Warning: file_get_contents(C:\wamp64\www\ticket-parser/templates\.): failed to open stream: Permission denied in C:\wamp64\www\ticket-parser\vendor\aymanrb\php-unstructured-text-parser\src\TextParser.php on line 76

I have access to that folders, it's the same Administrator user.

I did not tried in Linux but I will, any help?
Thanks

Edit:
I've added this to line 76 to validate and don't use 'file_get_contents' on a directory:

`if( !is_dir( $fileInfo->getPathname( ) ) ) $templates[$fileInfo->getPathname()] = file_get_contents($fileInfo->getPathname());`

**Comment by aymanrb** [comment]
Thank you for your contribution, I merged your pull request and it fixes the given warnings now
