### ISSUE TITLE
change default logs dir

### ISSUE THREAD

**Issue by ManiekPawel** [aymanrb/php-unstructured-text-parser#12]
Please add possibility to change default logs dir. Maybe in constructor as a optional value or in set method

**Comment by Beriw98** [comment]
I had same problem with logs. There is pull request with a feature.

**Comment by aymanrb** [comment]
Thanks for creating the issue @UserNameIsWrong and for your contribution and pull request @StarostaIZ.

Guess the implementation of injecting your own Logger (even if it was still Monolog with a different directory) is better than just limiting the choice to file logging. So I am happy to merge in the pull request, just have a request for a slight change if you can handle it and I will take it in.

Thank you.

**Comment by aymanrb** [comment]
Ok version [1.3.0] should now allow you to configure your own logger if needed and removed the forced monolog filesystem logging that was introduced in 1.1.0. The reason behind the removal is that logging wasn't always necessary (except for debugging and initial period run)

Thanks for the headsup and your contributions
