### ISSUE TITLE
Handle template without linefeed

### ISSUE THREAD

**Issue by nebuchadnezzar-network** [aymanrb/php-unstructured-text-parser#17]
Hi,
Thanks for an excellent text parser. 

I'm having issues with handling patterns where I like to capture the entire string after a selected word, but stop before linefeed. 

Example
`Offices: New York, London, Paris
Feel free to give us a call`

My template:
`Offices: {%Offices%}
Feel free to give us a call`

However the the next line would also be included. The only way to avoid this would be to include "Feel" in the template, but my source files are not consistent in what text will follow the "Offices" line. Is there a way to tell the parser to stop at CR/LF?

**Comment by aymanrb** [comment]
Well the point is given how usually dynamic the text files are the library prepares the parsing regex by flattening the files and templates into a single line before comparing and parsing ...

Usually in your template if you added something like:
```
Offices: {%Offices%}
{%extraText%}
```
It would have selected the text until the new line feed and everything else goes into the _extraText_ variable, but this is only possible in ideal world where whitespaces are guaranteed.

Whitespaces are removed in the following methods: 
- TextParser::prepareText()
- Helper\TemplatesHelper::prepareTemplate()

That's an interesting and a valid usecase though, so I will see if there is a way to instruct the parser to handle this differently when needed.

**Comment by aymanrb** [comment]
After investigating this a bit more, I am currently under the impression this flattening of the text is not even needed ! Since both the library's code and the usecases it was built for changed a lot in the past years I don't even know why was this needed.

I might remove this flattening and give it a try, will need you help @direktornswe  in testing this  when I am done if you don't mind.

**Comment by nebuchadnezzar-network** [comment]
Thanks @aymanrb 
Yes I did look at the code and discovered the whitespace removal. Currently I've just went to regular regex for this specific use case, but I'd rather have all my text functions in the same library. 

Currently just doing: 
`preg_match('/Offices:(.*)/',$Source, $matches);`

But I can participate testing if needed.

**Comment by aymanrb** [comment]
Thank you. I removed the whitespace stripping in this branch: **[bugfix/preserve-newlines-in-text](https://github.com/aymanrb/php-unstructured-text-parser/tree/bugfix/preserve-newlines-in-text)**

Could you please give it a try and see if it works for your usecase?

**Comment by nebuchadnezzar-network** [comment]
Sure. Tried it but didn't work. Outcome was the same, but it didn't change the linefeed. 

Master branch: 
```
Array
(
    [0] => Array
        (
            [City] => London Text after linefeed 
```

bugfix
```
Array
(
    [0] => Array
        (
            [City] => London

Text after linefeed 
```

As can be seen the whitespace has been removed, but the match still matches the text after the linefeed. \n in this case

My template is extremely simple: 
`Location: {%City%}`

**Comment by aymanrb** [comment]
Thank you for trying it out.

So In that case the template needs to instruct the variable when to stop, at least how I thought of it. So in the template if you add a new linefeed after the the variable, making it: 
```
Location: {%City%}

```

I would expect it to work then ! The idea is that you might have a multiple lines string that you want to gather all into one variable (like user comments or something) and it would then not make sense to forcefully limit the match to a single line, given you can manually force it in the template.

What do you think ?

**Comment by nebuchadnezzar-network** [comment]
I fully agree, what is the requirements for linefeed? 
I have tried to capture a linefeed but was not successful, is it OS agnostic? i.e linefeed = lf/cr?

**Comment by aymanrb** [comment]
Well I am not really sure how the text you want to parse looks like ... but now since the whitespaces are preserved I would say just add a new empty line to the template after the **Location: {%City%}** part ! 

You can check something similar in the examples folder: 
Template: t2.txt
Test File: m_2.txt

That's assuming you have one whole line of text you want to ignore after the City variable, if that's not the case you need to be more precise in the template and provide all the constant text to make it more accurate and reliable in parsing.

If you still can't get it to work, can you please send me few examples of the text you want to parse to "github@aymanrb.com" and I will try to create template(s) that can parse it reliably or fix the code further if that's needed !

**Comment by nebuchadnezzar-network** [comment]
Was the Template file uploaded? I can't find it.

**Comment by aymanrb** [comment]
It's in the new bug fix branch yes: 
- examples/templates/t_2.txt
- examples/test_txt_files/m_2.txt

**Comment by nebuchadnezzar-network** [comment]
Thanks. I got confused by worktree and branch a sec. 
Anyways the examples/test_txt_files/m_2.txt does not reflect how my file looks like so glad I could see it. 

If you add a linefeed and another line to examples/test_txt_files/m_2.txt after the comment line, that will be included in {%text%} variable and is exactly the problem I'm having.

**Comment by aymanrb** [comment]
Yep, exactly as I mentioned that's valid if everything else is only on one extra line. Anyway given the templates should work for generic cases I think we will need to be explicit about what comes next to the variable by any mean or else the regex won't know what to capture for that specific variable.

I would suggest you send me a 2+ different examples of the full text you are trying to parse and I will try to figure out a way to make it work :) or if you already have suggestions in mind feel free to propose it / implement it. 

The idea I had back then, and is still valid for my current usecases, is that you get a text that usually looks the same but has variables and needs to be parsed, so you build the template out of the text you get and replace everything that will be changing to variables (even if you will drop it later, just for the sake of simplicity).

So let's try to see if that's valid for your usecase or not, at least so far the whitespace removal that we originally manipulating the text you fetch blindly was not needed and should be removed.

**Comment by aymanrb** [comment]
Ok since this was a needed enhancement anyway, I merged the changes and will addit to the next release. If we still can't get it to work for your usecase we can perhaps look for a better way to implement the parsing.
