### ISSUE TITLE
Doubt php-unstructured-text-parser

### ISSUE THREAD

**Issue by sivakannan** [aymanrb/php-unstructured-text-parser#2]
First of all thanks for giving such a wonderful plugin. i have an small doubt that how can i parse dynamic data. now all the template is in static format ? can u pls advice for this ?

**Comment by aymanrb** [comment]
Yes, You create a static template to parse against dynamic (similar format) data. So you check where your dynamic data (variables) are and add a template variable notation `{%var_name%}` to it.
