### ISSUE TITLE
Template not Working

### ISSUE THREAD

**Issue by webgreat** [aymanrb/php-unstructured-text-parser#23]
Hello, 
```
$parser = new aymanrb\UnstructuredTextParser\TextParser('application/controllers/template');
$textToParse = 'hallo das ist ein test 4126552 und hier geht es weiter DFGHJKL mit dem Text ...';

//file_put_contents('application/controllers/template/test2.txt',$ordner['body']['html']);

print_r(
	$parser
		->parseText($textToParse,false )
		->getParsedRawData()
);

```

Template: 
`hallo das ist ein test {%name%} und hier geht es weiter {%namfe%} mit dem Text ...`

Return empty Array 
What am I doing wrong?

Mac OS M1
PHP 7.4

**Comment by aymanrb** [comment]
How are templates placed in the `application/controllers/template`, do you know if it is loaded ?

The template should be places in a **.txt** file directly under the above stated directory. The template should not contain any characters that doesn't match your expected text (even whitespace counts, unless you set the unknown characters to variables)

If I run your example here (also with PHP7.4) I get:
```
Array
(
    [name] => 4126552
    [namfe] => DFGHJKL
)

```

**Comment by webgreat** [comment]
Hello Mr. Bedair,
do you see the reason here?

![Bildschirmfoto 2021-11-13 um 17 17 21](https://user-images.githubusercontent.com/9807753/141651093-6cff9ae8-1ec2-43b4-83a4-5de6bb9cbe46.png)
![Bildschirmfoto 2021-11-13 um 17 18 47](https://user-images.githubusercontent.com/9807753/141651110-2134baa2-429d-42b8-b1a8-6a7afcbe11c1.png)

**Comment by aymanrb** [comment]
Looks good to me, the template is loaded and converted correctly to the regex ready to parse any text that matches.

The problem is the text doesn't match your template, the test text part ends with _...mit dem "**misst**"_ while the template is expecting a text that ends with _... mit dem "**Text**"_ in order to parse it correctly

**Comment by webgreat** [comment]
Thanks for your effort ..
Return empty Array 

![ Bildschirmfoto 2021-11-13 um 19 05 40](https://user-images.githubusercontent.com/9807753/141654440-4205bf3e-3aec-4fb9-a8be-57377c5d9d57.png)

**Comment by aymanrb** [comment]
Well I am really sorry it isn't that straightforward and for the trouble it's causing you to get it to work.

Given the idea of wanting this parser to handle quite a lot of different types of text and usecases of text to parse, and in many cases the templates would be quite similar with slight differences, it was built in a way that the template needs to exactly match the text it is intended to parse (or have anything that might vary as a variable in the template). 

In your case you are quite close now, there is still a slight difference, your text is all in one line, but the template expects a new line "**\n**" at the end after the words "mit dem Text".

In this case you need to edit your template file and remove the empty line and keep it as a 1 line template to match your text

**Comment by webgreat** [comment]
Hello Mr. Bedair,
I found out that PHPSTORM changed the Txt file when it was saved. It works wonderfully with nano editor.

Thank you for your time and this great lib.

**Comment by aymanrb** [comment]
Glad it worked at the end 🎊

Hope it works reliably on real examples and meets your expectations from it, and of not please let me know what didn't go well so we can think together on a way to make it cover more use cases.
