### ISSUE TITLE
Question: name of the selected chosen/best template

### ISSUE THREAD

**Issue by RobertEcker** [aymanrb/php-unstructured-text-parser#26]
Hi,
thank you for the project.

A question: Is it possible to get back the **name** of the automated chosen **template**?

Greets,
Robert

**Comment by aymanrb** [comment]
Hey @RobertEcker 
Yes that should be possible using the **getAppliedTemplateFile()** of the results object

https://github.com/aymanrb/php-unstructured-text-parser/blob/762cdaab8d0a9ecead78403b3568a5016d71c1d6/src/ParseResult.php#L24
