### ISSUE TITLE
Dynamic Template

### ISSUE THREAD

**Issue by chriskivaze** [aymanrb/php-unstructured-text-parser#7]
I'm glad i stumbled upon this very useful plugin . i have one question,can i parse dynamic data. and how do i handle it on the template file ?
Use case i have a template for orders each order has items(products),meaning one order can have 1 product another one can have 3 or more products,how do i parse each product as a variable? whats the best way to handle this?

**Comment by aymanrb** [comment]
Well the parser doesn't handle this use case (yet). At the end it is basically a regex extraction of text so this can be done by capturing a repeated group in regular expression.

If you can provide me with an example of your desired text for extraction I might try to fiddle around with it and see what I can get out of it.

**Comment by chriskivaze** [comment]
Hi Aymanrb,
The below is the two sample invoice txts from which we want to extract the data.The content after the line:
---------------------------------------------
is what we want to parse
[TSL1400073714031400020003_a.txt](https://github.com/aymanrb/php-unstructured-text-parser/files/1871903/TSL1400073714031400020003_a.txt)
[TSL1400073714031400020001_a.txt](https://github.com/aymanrb/php-unstructured-text-parser/files/1871904/TSL1400073714031400020001_a.txt)

**Comment by aymanrb** [comment]
I honestly can't see any pattern to work with here, that's just some random text that completely varies from one order to the other. I would have to write a specific custom parser for those. No simple regex would fit for those variances.

**Comment by chriskivaze** [comment]
Hi @aymanrb, I was able to handle the issue above.
Another thing I'm struggling with, I want to only parse text files that have not be parsed before(from the folder with text files- newer files),how can I best approach this

**Comment by aymanrb** [comment]
Answered in issue #8 - Parse only new files in a directory
