### ISSUE TITLE
Parse only new files in a directory

### ISSUE THREAD

**Issue by chriskivaze** [aymanrb/php-unstructured-text-parser#8]
I want to only parse text files that have not be parsed before(from the folder with text files- newer files),how can I best approach this

**Comment by aymanrb** [comment]
I would say there could be a number of ways to tackle this. The easiest and quickest way would be to move the parsed files into another directory as soon as you are done with it.
```
rename("unparsed/test.txt", "parsed/test.txt");
```
If moving the file is not possible for any reason Then you could rely on the file modification time of the file for example.
```
$lastParseTimeFile = 'lp_time.log';
$lastParseTimestamp = (int) file_get_contents($lastParseTimeFile);

$textFiles = new DirectoryIterator(__DIR__ . '/test_txt_files');
file_put_contents($lastParseTimeFile, time());

foreach ($textFiles as $txtFileObj) {
    if ($txtFileObj->getCTime() > $lastParseTimestamp) {
        //this is a new file, parse it ....
    }
}
```
There are still number of other ways, but I would say one of the above 2 examples should do it.

**Comment by chriskivaze** [comment]
Thanks for helping this worked perfectly
