### ISSUE TITLE
My Template Doesn't Work

### ISSUE THREAD

**Issue by Woxinn** [aymanrb/php-unstructured-text-parser#9]
My template is here.
```
{%title%}<br />
Türkçe Adı:{%name%}<br />
Soyadı:{%surname%}<br />
Telefon :{%phonenumber%}<br />
Faks:{%zip%}<br />
E-Posta:{%email%}<br />
Ağ:{%website%} <br />
Şirket:{%company%}<br />
Ülke: {%country%}<br />
<br />
{%description%}
```

And our input here.
```
020. Tunus'tan safran yağı alım talebi
Tunus'tan safran yağı alım talebi

Türkçe Adı: Zayani Karim
Soyadı:
Telefon: 0021625453108
Faks:
E-Posta: Zayanikarim11@gmail.com
Ağ:
Şirket: الجاذبية للاستيراد والتصدير Yerçekimi İthalat ve İhracat
Ülke: Tunus

اريد شراء زيت عطر الزعفران
Safran yağı almak istiyorum
```

why doesn't work?

**Comment by aymanrb** [comment]
Well to be honest the way this library works with regex makes it totally blind (it doesn't really try to solve / predict matches)

Your template needs to match the expected input text as much as you can and let in variables take control of areas you have doubt about (optional text for example)

2 things I would fix in your template in order it to make it work on the sample text your provided:

1- Removed the space after the **Telefon** key in the template. It should be Telefon: without a space between the work and the colon ":"

2- If you get the input as a plain text, like you pasted, then you need to remove the line break HTML tags. Only keep those if the input is HTML and has that exact same tag (check examples in the code)

A working template would then look like:

```
{%title%}

Türkçe Adı: {%name%}
Soyadı: {%surname%}
Telefon: {%phonenumber%}
Faks: {%zip%}
E-Posta: {%email%}
Ağ: {%website%}
Şirket: {%company%}
Ülke: {%country%}

{%description%}
```

**Comment by Woxinn** [comment]
Thanks for your help. But still doesn't work.

**Comment by Woxinn** [comment]
If you send me your email or another things, i can send you full codes.

**Comment by aymanrb** [comment]
Yep sure. Send it to: github@aymanrb.com
I am interested in the source input file you want to parse (the one that has the data in it). But definitely having a look at the code might help too.

**Comment by aymanrb** [comment]
Ok the matter was resolved by mail. Just for the records, there were 2 issues, the input was all in one file separated with a a delimiter that was wrongly defined in the code (resulting in wrong chunks to be parsed) and the input was not all in the same Layout / Format.

Both issues were resolved and now it gladly works as expected for @Woxinn :)
